server:
  port: 8081

spring:
  application:
    name: payment-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: payment
    password: payment
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  orchestrator:
    inbox-url: http://localhost:8080/api/inbox

outbox:
  relay:
    fixed-delay: 2000
    batch-size: 20
    max-attempts: 10

logging:
  level:
    com.gk3.demo: INFO
